[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Add plugin to install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Proxy API requests to our serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle SPA routing by redirecting all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[dev]
  command = "npm start" # Command to start your dev server
  port = 3006 # Changed from 3000 to avoid port conflicts
  publish = "build" # Folder with the static content for _redirect file

[functions]
  # Directory with serverless functions, including API
  directory = "netlify/functions"
  # 30 seconds is the maximum execution time for Netlify Functions on the free tier
  node_bundler = "esbuild"
  external_node_modules = ["express", "cors", "helmet", "morgan", "cookie-parser", "jsonwebtoken", "bcryptjs", "@supabase/supabase-js"] 